---
pipeline:
  build:
    image: "docker:17.07.0"
    environment:
      - "DOCKER_HOST=tcp://dind:2375"
    commands:
      - env
      - sleep 10
      - docker info

services:
  dind:
    image: "docker:17.07.0-dind"
    privileged: true
    command:
      # - "--host"
      # - "tcp://0.0.0.0:2375"
      - "-s"
      - "overlay"
