---
pipeline:
  build:
    image: "docker:17.07.0"
    environment:
      - "DOCKER_HOST=tcp://172.17.0.1:2375"
    commands:
      - docker info
      - docker run --rm radial/busyboxplus:curl http://nginx

services:
  nginx:
    image: nginx
