---
pipeline:
  build:
    image: "docker:17.07.0"
    environment:
      - "DOCKER_HOST=tcp://dind:2375"
    commands:
      - env
      - docker info

services:
  dind:
    image: "docker:17.07.0-dind"
    privileged: true
    entrypoint: ["dockerd"]
    command:
      - "-D"
      - "-s"
      - "overlay"
