---
pipeline:
  build:
    image: "docker:17.07.0"
    environment:
      - "DOCKER_HOST=tcp://172.17.0.1:2375"
    commands:
      - env
      - docker info

# services:
#   dind:
#     image: "docker:17.07.0-dind"
#     privileged: true
#     command:
#       - "-s"
#       - "overlay"
#       
