---
pipeline:
  build:
    image: "docker:17.07.0"
    environment:
      - "DOCKER_HOST=tcp://172.17.0.1:2375"
    commands:
      - cat /etc/resolv.conf
      - cat /etc/hosts
      # - docker ps
      # - docker network ls
      - "docker inspect $(docker ps -q)"
      - "docker run --dns 127.0.0.11 --rm alpine cat /etc/resolv.conf"
      - "docker run --dns 127.0.0.11 --rm alpine cat /etc/hosts"
      # - "docker run --dns 127.0.0.11 --rm byrnedo/alpine-curl http://nginx:80"

  # curl:
  #   image: "fedora:26"
  #   environment:
  #     - "DOCKER_HOST=tcp://172.17.0.1:2375"
  #   commands:
  #     - curl http://nginx:80

# services:
#   nginx:
#     image: nginx
