---
pipeline:
  build:
    image: "docker:17.07.0"
    network_mode: bridge
    environment:
      - "DOCKER_HOST=tcp://172.17.0.1:2375"
    commands:
      - env
      - docker ps
      - docker network ls
      - "docker run --rm byrnedo/alpine-curl http://nginx:80"

services:
  network_mode: bridge
  nginx:
    image: nginx
